### ISSUE TITLE
Error: Post /services/oauth2/token: unsupported protocol scheme "" 

### ISSUE THREAD

**Issue by matthewleahy** [skuid/skuid#12]
Unable to execute skuid command without the "--host" flag. 

Commands: 
skuid pull -m Dashboard 
skuid pull -m Dashboard --host my-domain.my.salesforce.com

Error: 
Post /services/oauth2/token: unsupported protocol scheme "" 

Works with "https://" + "my-domain.my.salesforce.com"

Command: skuid pull -m Dashboard --host https://my-domain.my.salesforce.com

New to this, so may be missing configuration somewhere.

**Comment by zachelrath** [comment]
This looks like an inconsistency in our documentation - we should either change the documentation and/or make the CLI more resilient to handle hosts without a protocol (i.e. prepend `https://` if there's no protocol)

**Comment by zachelrath** [comment]
In 0.3.8 we are providing better error messaging that informs you when / if the Host, Username, and Password parameters are not provided, and we are also automatically prepending "https://" to the host if it is not provided.
