### ISSUE TITLE
skuid with -v flag reports login was successful when it was not.

### ISSUE THREAD

**Issue by itmightbecody** [skuid/skuid#13]
While retrieving and deploying to a few different Skuid sites, I didn't update my password env var. When I ran `skuid retrieve` I got the expected `Error retrieving metadata:  Error making HTTP request%!(EXTRA string=401 Unauthorized)` message. 

However I ran `skuid retrieve -v` just to double check, and it said that I had successfully logged in:

```
Logging in to Skuid Platform...
Host: {my-skuid-site}
Username: {username}
Password: {incorrect-password}
API Version: 1
Login successful! Access Token:
Retrieving metadata...
Error retrieving metadata:  Error making HTTP request%!(EXTRA string=401 Unauthorized)

```

For the sake of accurate debugging, the app should correctly report whether or not login was successful.

**Comment by zachelrath** [comment]
Thanks for reporting this Cody, yeah it's inaccurate for Skuid to say that the login failed if no access token was retrieved. Should be an easy improvement.
