### ISSUE TITLE
skuid cli not pulling all pages

### ISSUE THREAD

**Issue by pogilvie** [skuid/skuid#20]
Hello I just configured the skuid cli for a new client sandbox.    

1) skuid pull -v
Pages written to skuidpages

2) no errors echo $?
0

There are over 80 pages in the org and I'm only getting 10 pages back.  I noticed that the pages I'm getting back are pages where I'm the owner.  So I changed the owner of a few other pages and I'm still getting the same set of 10 pages back.

I've used the cli in other orgs w/o issue.   What should I do to get all 80 pages pulled?

Thanks,
Peter

**Comment by plusplusben** [comment]
Hmmm, anything special about those 10 pages? Are they all in the same module? Do you happen to have an environment variable set that specifies a module?

**Comment by pogilvie** [comment]
What seems to be special about them is that they were all owned/created by me.  The other pages where there from the sandbox refresh and owned by another user.    I tried going in an updating the skuid__page__c record of one of these other pages to be owned by me and it still didn’t download.  I don’t have a module filter set at all.    I try and debug this I built the skuid/skuid tool from source.

I get the following error from the tool I built off master:

./skuid pull
"{\"error\":\"You must provide a \\\"module\\\" URL Parameter containing the names of the Modules of Pages (comma-separated) AND/OR a \\\"page\\\" URL Parameter containing the names of the Pages (comma-separated) you would like to retrieve.\"}"
json: cannot unmarshal string into Go value of type types.PullResponse


My current theory is that this is not an issue with the tool but rather the the API call:

//query the API for all pages in the requested module
result, err := api.Connection.Get("/skuid/api/v1/pages", query)

is not returning all the pages.  I wish I could print out query but the version I build bombs out.

Thanks,
Peter

**Comment by plusplusben** [comment]
Usually the "unsupported protocol scheme" error means that the SKUID_HOST environment variable isn't set correctly. I think it needs to have "https://" in the beginning of its value.

**Comment by zachelrath** [comment]
In 0.3.8 we are providing better error messaging that informs you when / if the Host, Username, and Password parameters are not provided, and we are also automatically prepending "https://" to the host if it is not provided.
