### ISSUE TITLE
skuid pull in 0.3.0

### ISSUE THREAD

**Issue by jinlii** [skuid/skuid#23]
skuid is alias for skuid_windows_amd64.exe on Windows and for skuid_darwin_amd64 on Mac

I tried this command on both Windows and Mac and it fails:
skuid pull --host https://<Domain>.my.salesforce.com -n PageName -v

Error:
"{\"error\":\"You must provide a \\\"module\\\" URL Parameter containing the nam
e, or comma-separated names, of the Modules of pages you would like to retrieve\
"}"
json: cannot unmarshal string into Go value of type types.PullResponse

This command works:
skuid pull --host https://.my.salesforce.com -m ModuleName

**Comment by zachelrath** [comment]
Jill, what Skuid release do you have installed in your org? The ability to pull specific pages by name may not be available in the release of Skuid that is in your org.

**Comment by jinlii** [comment]
Rockaway is the version.

**Comment by itmightbecody** [comment]
Hi @jinlii, the ability to pull Skuid pages by name requires the Millau Update 2 release ([v11.2.0 or above](https://docs.skuid.com/v11.2.0/en/release-notes.html#minor-updates)).  You'll need to upgrade the Skuid managed package within the Salesforce org to use the `--page` or `-n` command flag. 

While [upgrading to the latest release](https://docs.skuid.com/latest/en/skuid/best-practices/upgrade-skuid.html) is always recommended if feasible, here's a workaround for Rockaway: you can create [a module](https://docs.skuid.com/latest/en/skuid/pages/create-module.html), assign the page(s) to that module, and then utilize the `--module` command flag to pull the page(s) you need.

Hope this helps!

**Comment by jakubmplatek** [comment]
Hi,
I'm getting this error when running skuid pull with no additional parameters, i.e. attempting to pull all pages in the org.
We're on Millau (11.2.10) and I'm using CLI 0.3.2

The error message after upgrading from 11.0.2 to 11.2.10 changed to:
$ skuid pull -v
"{\"error\":\"You must provide a \\\"module\\\" URL Parameter containing the names of the Modules of Pages (comma-separated) AND/OR a \\\"page\\\" URL Parameter containing the names of the Pages (comma-separated) you would like to retrieve.\"}"
json: cannot unmarshal string into Go value of type types.PullResponse

When running for a single page it works without a module, but not without any params; the documentation at https://docs.skuid.com/latest/en/skuid/cli doesn't specify --module as a required parameter, and the included example suggests $ skuid pull should work fine. 
Please let me know what's the roadmap for this, cause we're working on a larger CI automation around the CLI.

**Comment by plusplusben** [comment]
@jakubmplatek I'm taking a look at this now.

**Comment by plusplusben** [comment]
@jakubmplatek This is a bug that was introduced in 11.2.0. We will have this bug fixed in a maintenance  release of 11.2.

**Comment by zachelrath** [comment]
This was fixed in [Millau 11.2.12](www.skuid.com/releases/salesforce) - please install either the latest Millau or Spark release in order for the fix to have an effect on your Salesforce org.
